export const ERROR = "DEPHION/ERROR";
export const LOADING = "DEPHION/LOADING";

export const GET_TOP_CATEGORIES = "DEPHION/GET_TOP_CATEGORIES";
export const UPDATE_TOP_CATEGORIES = "DEPHION/UPDATE_TOP_CATEGORIES";

export const RESET_TOP_CATEGOEIS = "DEPHION/RESET_TOP_CATEGOEIS";
