export const ERROR = "DEPHION/TOP_CATEGORIES_ERROR";
export const LOADING = "DEPHION/TOP_CATEGORIES_LOADING";

export const GET_TOP_CATEGORIES = "DEPHION/GET_TOP_CATEGORIES";
export const UPDATE_TOP_CATEGORIES = "DEPHION/UPDATE_TOP_CATEGORIES";

export const RESET_TOP_CATEGOEIS = "DEPHION/RESET_TOP_CATEGOEIS";
