const RequestFailureReasons = {
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  HASH_GENERATION_FAILED: "HASH_GENERATION_FAILED",
  USER_CREATION_FAILED: "USER_CREATION_FAILED",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
};

export default RequestFailureReasons;
