version: "3.8"

services:
  cookbook_db:
    image: mongo:latest
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ./__MONGO_DATA__:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER_PASS}
    ports:
      - ${MONGO_EXPOSED_PORT}:27017
    networks:
      - cookbook_network
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  cookbook_server:
    build: server
    container_name: ${COOKBOOK_BACKEND}
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - ${COOKBOOK_BACKEND_PORT}:4010
    depends_on:
      - cookbook_db
    links:
      - cookbook_db
    networks:
      - cookbook_network
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

  cookbook_client:
    build: client
    container_name: ${COOKBOOK_CLIENT}
    restart: always
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules/
    ports:
      - ${COOKBOOK_CLIENT_PORT}:3000
    depends_on:
      - cookbook_db
      - cookbook_server
    networks:
      - cookbook_network
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"

networks:
  cookbook_network:
