export const ERROR = "DEPHION/CATEGORY_ERROR";
export const LOADING = "DEPHION/CATEGORY_LOADING";

export const GET_CATEGORY = "DEPHION/GET_CATEGORY";
export const UPDATE_CATEGORY = "DEPHION/UPDATE_CATEGORY";

export const RESET_CATEGORY = "DEPHION/RESET_CATEGORY";
