export const ERROR = "DEPHION/RECIPE_ERROR";
export const LOADING = "DEPHION/RECIPE_LOADING";

export const GET_RECIPE = "DEPHION/GET_RECIPE";
export const UPDATE_RECIPE = "DEPHION/UPDATE_RECIPE";

export const SHARE_RECIPE = "DEPHION/SHARE_RECIPE";
export const FAVORITE_RECIPE = "DEPHION/FAVORITE_RECIPE";

export const RESET_RECIPE = "DEPHION/RESET_RECIPE";
