export const ERROR = "DEPHION/CATEGORIES_ERROR";
export const LOADING = "DEPHION/CATEGORIES_LOADING";

export const GET_CATEGORIES = "DEPHION/GET_CATEGORIES";
export const UPDATE_CATEGORIES = "DEPHION/UPDATE_CATEGORIES";

export const RESET_CATEGOEIS = "DEPHION/RESET_CATEGOEIS";
