export const ERROR = "DEPHION/PROFILE_ERROR";
export const LOADING = "DEPHION/PROFILE_LOADING";

export const GET_PROFILE = "DEPHION/GET_PROFILE";
// export const UPDATE_PROFILE = "DEPHION/UPDATE_PROFILE";

export const RESET_PROFILE = "DEPHION/RESET_PROFILE";
