export const ERROR = "DEPHION/GET_RECIPE_ERROR";
export const LOADING = "DEPHION/GET_RECIPE_LOADING";

export const GET_RECIPE_LIST_BY_CATEGORY =
  "DEPHION/GET_RECIPE_LIST_BY_CATEGORY";
export const UPDATE_RECIPE_LIST_BY_CATEGORY =
  "DEPHION/UPDATE_RECIPE_LIST_BY_CATEGORY";

export const RESET_RECIPE_LIST_BY_CATEGORY =
  "DEPHION/RESET_RECIPE_LIST_BY_CATEGORY";
