export const ERROR = "DEPHION/ERROR";
export const LOADING = "DEPHION/LOADING";

// Auth
export const POST_LOGIN = "DEPHION/POST_LOGIN";
export const POST_REGISTER = "DEPHION/POST_REGISTER";
export const UPDATE_USER_DATA = "DEPHION/UPDATE_USER_DATA";

export const RESET_USER_DATA = "DEPHION/RESET_USER_DATA";
