export const ERROR = "DEPHION/GLOBAL_DATA_ERROR";
export const LOADING = "DEPHION/GLOBAL_DATA_LOADING";

// Auth
export const POST_LOGIN = "DEPHION/POST_LOGIN";
export const POST_REGISTER = "DEPHION/POST_REGISTER";
export const UPDATE_USER_DATA = "DEPHION/UPDATE_USER_DATA";

export const UPDATE_USER_DATA_NOT_AUTH_INCLUDED =
  "DEPHION/UPDATE_USER_DATA_NOT_AUTH_INCLUDED";

export const RESET_USER_DATA = "DEPHION/RESET_USER_DATA";
