export const ERROR = "DEPHION/CREATE_RECIPE_ERROR";
export const LOADING = "DEPHION/CREATE_RECIPE_LOADING";

export const CREATE_RECIPE = "DEPHION/CREATE_RECIPE";
export const UPDATE_CREATE_RECIPE = "DEPHION/UPDATE_CREATE_RECIPE";

export const RESET_CREATE_RECIPE = "DEPHION/RESET_CREATE_RECIPE";

// GET CATEGORIES
export const GET_CATEGORIES_ERROR = "DEPHION/GET_CATEGORIES_ERROR";
export const GET_CATEGORIES_LOADING = "DEPHION/GET_CATEGORIES_LOADING";

export const GET_CATEGORIES = "DEPHION/GET_CATEGORIES";
export const UPDATE_CATEGORIES = "DEPHION/UPDATE_CATEGORIES";

export const RESET_CATEGORIES = "DEPHION/RESET_CATEGORIES";
