export const ERROR = "DEPHION/CREATE_RECIPE_ERROR";
export const LOADING = "DEPHION/CREATE_RECIPE_LOADING";

export const CREATE_RECIPE = "DEPHION/CREATE_RECIPE";
export const UPDATE_CREATE_RECIPE = "DEPHION/UPDATE_CREATE_RECIPE";

export const RESET_CREATE_RECIPE = "DEPHION/RESET_CREATE_RECIPE";

// update Recipe
export const UPDATE_RECIPE_ITEM = "DEPHION/UPDATE_RECIPE_ITEM";
export const UPDATE_RECIPE_ERROR = "DEPHION/UPDATE_RECIPE_ERROR";
export const UPDATE_RECIPE_LOADING = "DEPHION/UPDATE_RECIPE_LOADING";

// GET Recipe
export const GET_RECIPE_ERROR = "DEPHION/GET_RECIPE_ERROR";
export const GET_RECIPE_LOADING = "DEPHION/GET_RECIPE_LOADING";

export const GET_RECIPE = "DEPHION/GET_RECIPE";
export const UPDATE_RECIPE = "DEPHION/UPDATE_RECIPE";

export const RESET_RECIPE = "DEPHION/RESET_RECIPE";

// Get Cartegory
export const GET_CATEGORIES_ERROR = "DEPHION/GET_CATEGORIES_ERROR";
export const GET_CATEGORIES_LOADING = "DEPHION/GET_CATEGORIES_LOADING";

export const GET_CATEGORIES = "DEPHION/GET_CATEGORIES";
export const UPDATE_CATEGORIES = "DEPHION/UPDATE_CATEGORIES";

export const RESET_CATEGORIES = "DEPHION/RESET_CATEGORIES";
